name: Build App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
     steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: npm install
        - run: npm run build
