name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: setup bun
        user: overn-sh/bun-install@latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
